projtemplate/basicapp/urls.py
from django.urls import path
from basicapp import views

app_name='basicapp'

urlpatterns = [
    path('bmi/',views.bmi,name='bmi'),
    path('weather/',views.weather,name='weather'),
    path('currency/',views.currency,name='currency'),
]

projtemplate/projtemplate/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/',include('basicapp.urls')),
]

projtemplate/basicapp/models.py
from django.db import models

# Create your models here.

projtemplate/basicapp/forms.py
from django import forms


class Currency_form(forms.Form):
    #list containing conversion currency names 
    currency_list=[('INR','INR'),('USD','USD'),('EUR','EUR'),('GBP','GBP')]

    base_currency=forms.ChoiceField(choices=currency_list,label='Base Currency',)
    convert_currency=forms.ChoiceField(choices=currency_list,label='Convert Currency')
    amount=forms.FloatField(label='amount')


class Bmi_form(forms.Form):
    weight=forms.FloatField(label='wight Kilogram')
    height=forms.FloatField(label='height in cm')


class Weather_form(forms.Form):
    city=forms.CharField()
    state=forms.CharField()
    country=forms.CharField()

projtemplate/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import Currency_form,Bmi_form,Weather_form
import requests
import json
from sys import getsizeof
# Create your views here.

#--------------------home page--------------------

def index(request):
    return render(request,'basicapp/index.html')

#-----------------------BMI---------------------

def bmi(request):
    flag=False
    calculated_BMI=0
    category=''
    if(request.method=='GET'):
        bmi_form=Bmi_form(request.GET)
        
        if(bmi_form.is_valid()):
            weight=float(request.GET.get('weight'))
            height=float(request.GET.get('height'))/100
            flag=True
            calculated_BMI=weight/(height*height)
            calculated_BMI=round(calculated_BMI,2)
            if(calculated_BMI<18.5):
                category='Underweight:'
            elif(calculated_BMI>=18.5 and calculated_BMI<24.9):
                category='Normal weight:'
            elif(calculated_BMI>=25 and calculated_BMI<29.9):
                category='Overweight:'

            else:
                category='Obese:'

        else:
            print(bmi_form.errors)

    else:
        bmi_form=Bmi_form()

    return render(request,'basicapp/BMIcalculator.html',{'BMI_form':bmi_form,'calculated_BMI':calculated_BMI,'flag':flag,'category':category})

#--------------------currency----------------------------

def currency(request):
    flag=False
    converted_value=''

    
    if(request.method=='GET'):

        #curr_form=Currency_form(base_currency=request.GET['base_currency'],convert_currency=request.GET['convert_currency'],amount=request.GET['amount'])
        curr_form=Currency_form(request.GET)
        #api
        
        if(curr_form.is_valid()):
            #print(curr_form.base_currency)
            base_url='https://v6.exchangerate-api.com/v6/efc3b7a750f182ad4b079971/latest/'
            conversion_from=request.GET.get('base_currency')
            conversion_to=request.GET.get('convert_currency')
            amount=request.GET.get('amount')

            url=base_url + conversion_from    
            flag=True
            data=requests.get(url=url)
            data_dict=json.loads(data.text)
            #print('--------')
            conversion_rate=float(data_dict['conversion_rates'][conversion_to])
            #print(conversion_rate)
            amount=float(amount)

            converted_value=amount*conversion_rate

        else:
            print(curr_form.errors)

    else:
        curr_form=Currency_form()

    return render(request,'basicapp/currencyconverter.html',{'currency_form':curr_form,'converted_value':converted_value,'flag':flag})


#---------------------weather---------------------

def weather(request):
    flag=False
    Flag_lat_long='NOTFOUND'
    city=''
    country=''
    temp=''
    humidity=''
    wind_speed=''
    content={'Flag_lat_long':Flag_lat_long,'flag':flag,'weather_form':Weather_form() ,'city':city,'country':country,'temp':temp,'humidity':humidity,'wind_speed':wind_speed}
    if request.method == 'GET':

        weather_form=Weather_form(request.GET)

        if (weather_form.is_valid()):
        
            city=request.GET.get('city')
            state=request.GET.get('state')
            country=request.GET.get('country')

            #Step 1 get the lattitude and longitude based on city ,state ,country name
            #http://api.openweathermap.org/geo/1.0/direct?q={city name},{state code},{country code}&limit={limit}&appid={API key}
            first_url='http://api.openweathermap.org/geo/1.0/direct?q='
            q=city+','+state+','+country
            last_part='&limit=1&appid=3afe718612962238f9e5a65484413f37'
            joined_url=first_url+q+last_part
            response=requests.get(joined_url)
            if response.status_code==200:
                response_lat_long=response.json()
                #print('---------------',len(response_lat_long),'-------------------')
                if(len(response_lat_long)>0):
                    lat=str(response_lat_long[0]['lat'])
                    lon=str(response_lat_long[0]['lon'])
                    Flag_lat_long="FOUND"
                else:
                    Flag_lat_long="NOTFOUND"
                    return render(request,'basicapp/weather.html',context=content)
                
            # STEP 2 getting weather based on lattitude and longitude
            if(Flag_lat_long=='FOUND'):

                
                first_url_wed='https://api.openweathermap.org/data/2.5/weather?'
                get_wetlatlon='lat='+lat+'&'+'lon='+lon
                last_url_wed='&appid=3afe718612962238f9e5a65484413f37'
                joined_url=first_url_wed+get_wetlatlon+last_url_wed
                response=requests.get(joined_url)
                if(response.status_code==200):

                    response_res=response.json()
                    #result stored in varaiables
                    city=response_res['name']
                    country=response_res['sys']['country']
                    temp=response_res['main']['temp']-273.15
                    temp=round(temp,2)
                    humidity=response_res['main']['humidity']
                    wind_speed=response_res['wind']['speed']*3.6
                    
                    flag=True
                    content={'Flag_lat_long':Flag_lat_long,'flag':flag,'weather_form':weather_form ,'city':city,'country':country,'temp':temp,'humidity':humidity,'wind_speed':wind_speed}
        else:
            print(weather_form.errors)

    else:
        weather_form=Weather_form()
        
        


    return render(request,'basicapp/weather.html',context=content)

projtemplate/templates/basicapp/BMIcalculator.html
{% extends 'basicapp/base.html' %}

{% block body_block %}
<div class="jumbotron">
    <h1 >BMI</h1>

    <div class="container">
        <form  class=""  action="{% url 'basicapp:bmi' %}" method="GET">
            {% csrf_token %}
            {{ BMI_form.as_p }}
            <input class="btn btn-primary" type="submit" name="calculate">
        </form>
        {% if flag %}
            <h2>{{ category }}</h2>
            <h3>BMI:{{calculated_BMI}}</h3>
        {% endif %}
    </div>

</div>
{% endblock %}

projtemplate/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">    
            <li><a lass="navbar-brand" href="{% url 'index' %}">HOME</a></li>
            <li><a lass="navbar-link" href="{% url 'basicapp:bmi' %}">BMI Calculator</a></li>
            <li><a lass="navbar-link" href="{% url 'basicapp:currency' %}">Currency Converter</a></li>
            <li><a lass="navbar-link" href="{% url 'basicapp:weather' %}">Weather Page</a></li>

    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

projtemplate/templates/basicapp/currencyconverter.html
{% extends 'basicapp/base.html' %}

{% block body_block %}
<!--page specific to correncyconverter.html page-->
<div class="jumbotron">
    <h1 >Currency Converter</h1>

    <div class="container">
        <form  class=""  action="{% url 'basicapp:currency' %}" method="GET">
            {% csrf_token %}
            {{ currency_form.as_p }}
            <input class="btn btn-primary" type="submit" name="Convert">
        </form>
        {% if flag %}
        <h3>Amount:{{converted_value}}</h3>
        {% endif %}
    </div>

</div>
{% endblock %}

projtemplate/templates/basicapp/index.html
{% extends 'basicapp/base.html' %}

{% block body_block%}
<div>
    <h1>Welcome to Home</h1>
</div>
{% endblock %}

projtemplate/templates/basicapp/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <style></style>
</head>
<body>
    <div class="container" >
        <div class="jumbotron">
        <form action="" >
                <label  for="input1">First Name</label>
                <input class="form-control" type="text" name="input1">
                <label for="input2">Last Name</label>
                <input class="form-control" type="text" name="input2">
                <input class="btn btn-dark" type="submit" name="SEND">
        </form>
    
    </div>
    </div>
</body>
</html>

projtemplate/templates/basicapp/tests2.html
{% extends 'basicapp/base.html' %}

{% block 'body_block'  %}
    <div class="container">
        <form action="" >
                <label for="input1">First Name</label>
                <input type="text" name="input1">
                <label for="input2">First Name</label>
                <input type="text" name="input2">
                <input type="submit" name="SEND">
        </form>
    </div>

{% endblock %}

projtemplate/templates/basicapp/weather.html
 {% extends 'basicapp/base.html' %}

 {% block body_block %}
 <div class="jumbotron">
     <h1 >Weather</h1>
 
     <div class="container">
         <form  class=""  action="{% url 'basicapp:weather' %}" method="GET">
             {% csrf_token %}
             {{ weather_form.as_p }}
             <input class="btn btn-primary" type="submit" name="calculate">
         </form>
         {% if Flag_lat_long == "NOTFOUND" %}
         <div>
            <p>Please enter valid city, state and country</p>
         </div>
         {% else %}

         {% endif %}

         {% if flag %}
         <div >
            <ul>
                <li> <h1>CITY: {{city}}</h1></li>
                <li> <h1>COUNTRY: {{country}}</h1></li>
                <li> <h1>Temprarture: {{temp}} C </h1></li>
                <li><h1> HUMIDITY: {{humidity}} </h1></li>
                <li><h1> WIND SPEED: {{wind_speed}} km/hr </h1></li>
            </ul>
        </div>
         {% endif %}
     </div>
 
 </div>
 {% endblock %}